server:
  port: 8300
spring:
  application:
    name: consumer-hystrix-tubine4
user:
  url: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:20000/eureka

  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    cluster-config: CONSUMER-ORDER-FEIGN-HYSTRIX-TURBINE2
  app-config: consumer-order-feign-hystrix-turbine2


