server:
  port: 8300
spring:
  application:
    name: consumer-hystrix-tubine2
user:
  url: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:20000/eureka

  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    cluster-config: default
  app-config: consumer-order-hystrix,consumer-order-feign-hystrix
  cluster-name-expression: "'default'"

