server:
  port: 7900 #程序启动后的端口，也就是tomcat的端口，可以自己定义
spring:
  application:
    name: provider-user #应用名称，别名
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:20000/eureka
  instance:
    ip-address: true
security:
  basic:
    enabled: true #开启安全配置，也就是需要密码，如果不需要设置为false
  user:
    name: user
    password: 123 #在设置用户密码后，我们可以修改地址访问风格为CURL風格
